reed/catalog/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register('book', views.BookViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls, namespace='bookapi'), name='book-api'),
    url(r'^$', views.book_list,
        name='book-list'),
    url(r'^(?P<book_id>\d+)/$', views.book_detail,
        name='book-detail'),
    url(r'^search/$', views.search,
        name='book-search'),
    url(r'^intro-python/$', views.intro_python,
        name='intro-python'),
]

reed/reed/urls.py
from django.conf.urls import include, url
from catalog import urls as catalog_urls
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^books/', include(catalog_urls, namespace='catalog')),
    url(r'^$', views.homepage, name='home')
]

reed/catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.contrib.auth.models import User

from .queryset import BookQuerySet


class Book(models.Model):
    isbn13 = models.CharField(max_length=13)
    title = models.CharField(max_length=200)
    description = models.TextField()
    authors = models.ManyToManyField('catalog.Author')
    publisher = models.ForeignKey('catalog.Publisher')

    objects = BookQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('catalog:book-detail', args=(self.pk,))

    def __str__(self):
        return self.title

class Publisher(models.Model):
    name = models.CharField(max_length=100)
    address = models.TextField()
    website = models.URLField()

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

reed/hello/models.py
from django.db import models

# Create your models here.

reed/catalog/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()

    def clean_query(self):
        query = self.cleaned_data['query']
        if len(query) < 3:
            raise forms.ValidationError('Query too short, min 3 characters')
        return query

reed/catalog/views.py
from django.shortcuts import render

from rest_framework import viewsets

from .models import Book
from . import forms
from . import serializers


def book_list(request):
    books = Book.objects.all()
    context = {
        'books': books,
    }
    return render(request, 'catalog/book_list.html', context)

def book_detail(request, book_id):
    book = Book.objects.get(pk=book_id)
    context = {
        'book': book,
    }
    return render(request, 'catalog/book_detail.html', context)

def intro_python(request):
    books = Book.objects.python_book().intro_book()
    context = {
        'books': books,
    }
    return render(request, 'catalog/book_list.html', context)


def search(request):
    context = {}
    if 'query' in request.GET:
        form = forms.SearchForm(request.GET)
        context['form'] = form
        if form.is_valid():
            context['books'] = Book.objects.filter(title__icontains=form.cleaned_data['query'])
        else:
            context['books'] = Book.objects.none()
    else:
        context['form'] = forms.SearchForm()
        context['books'] = Book.objects.none()
    return render(request, 'catalog/book_search.html', context)

class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = serializers.BookSerializer

reed/hello/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'hello.html')

reed/reed/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'index.html')

reed/catalog/templates/catalog/base.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'catalog:book-list' %}">All Books</a> - 
<a href="{% url 'catalog:book-search' %}">Search Books</a> -
<a href="{% url 'catalog:intro-python' %}">Python Books (Beginner)</a> -
<a href="{% url 'catalog:bookapi:api-root' %}">API</a> 
{% endblock content %}

reed/catalog/templates/catalog/book.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ book.title }} - <small>{{ book.isbn13 }}</small></h2>
<q>{{ book.description }}</q>
{% endblock content %}

reed/catalog/templates/catalog/book_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{{ block.super }}
<h2>{{ book.title }} - <small>{{ book.isbn13 }}</small></h2>
<q>{{ book.description }}</q>
{% endblock content %}

reed/catalog/templates/catalog/book_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{{ block.super }}
<ul>
  {% for book in books %}
  <li><a href="{{ book.get_absolute_url }}">{{ book.title }} - {{ book.isbn13 }}</a></li>
  {% endfor %}
</ul>
{% endblock content %}

reed/catalog/templates/catalog/book_search.html
{% extends 'catalog/base.html' %}

{% block content %}
{{ block.super }}
<form action='' method='get'>
  {{ form }}
  <input type='submit' value='Search' />
</form>
<ul>
  {% for book in books %}
  <li><a href="{{ book.get_absolute_url }}">{{ book.title }} - {{ book.isbn13 }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

reed/catalog/templates/catalog/index.html
{% extends 'base.html' %}
{% block content %}
<ul>
  {% for book in books %}
  <li><a href="{{ book.get_absolute_url }}">{{ book.title }} - {{ book.isbn13 }}</a></li>
  {% endfor %}
</ul>
{% endblock content %}

reed/hello/templates/hello.html
<h1>Hello World</h1>

reed/templates/base.html
<html>
  <head>
  </head>
  <body>
    <h1><a href="{% url 'home' %}">Django 101</a> - Personal Library</h1>
    {% block content %}
    {% endblock content %}
  </body>
</html>

reed/templates/index.html
{% extends 'base.html' %}
{% block content %}
<p>Welcome to Personal Library</p>
<a href="{% url 'catalog:book-list' %}">Catalog Listing</a>
{% endblock %}